server:
  port: 8765

spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://cxytiandi.com
          predicates:
            - Path=/course
#  cloud:
#    config:
#      name: ${spring.application.name}
#      profile: dev
#      uri: 'http://localhost:8763'
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    instance:
#      lease-expiration-duration-in-seconds: 30
#      lease-renewal-interval-in-seconds: 10

#management:
#  endpoints:
#    web:
#      exposure:
#        include: shutdown
#  endpoint:
#    shutdown:
#      enabled: true