server:
  port: 8764

spring:
  application:
    name: ADMIN-SERVER
  security:
    user:
      name: "root"
      password: "password"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10