server:
  port: 8765
spring:
  application:
    name: SERVICE-FEIGN
  boot:
    admin:
      client:
        url: http://localhost:8791
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"