spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://demo:3306/finalfantasyxiv?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: fell
    password: finalfantasyxiv
  mail:
    host: smtp.qq.com
    username: 544107559@qq.com
    password: kxxochmhfkaybfhi
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    port: 6379
    host: demo
    password: finalfantasyxiv
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 300

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.servicehi.entity

uploadImagePath:
  windows: 'D:/images'
  linux: '/usr/local/app/static/uploadImage'
  linuxPath: '/static/uploadImage'

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.example.servicehi.controller: info
    com.example.servicehi.dao: debug

delete_old_auth: true #删除旧权限

wechat:
  mp-app-id: wx180cb4037e983551
  mp-app-secret: cf0bf3e4c546ded33dcd54b4290c145c
  token: FinalFantasyXIV

searchIPWebSite: 'http://2019.ip138.com/ic.asp'