server:
  port: 8089
spring:
  application:
    name: ADMIN-CLIENT
  boot:
    admin:
      client:
        url: http://localhost:8791
management:
  endpoints:
    web:
      exposure:
        include: "*"