server:
  port: 8089
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8091
management:
  endpoints:
    web:
      exposure:
        include: "*"