server:
  port: 8762

spring:
  application:
    name: service-hi
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://demo:3306/finalfantasyxiv?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: fell
    password: finalfantasyxiv
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    port: 6379
    host: demo
    password: finalfantasyxiv
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 300

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    #注意下面这个位置！！
#    enabled-by-default: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.servicehi.entity

uploadImagePath:
  windows: 'D:\\images\\'
  linux: '/usr/local/app/static/uploadImage/'
  linuxPath: '/static/uploadImage/'

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

delete_old_auth: true #删除旧权限

searchIPWebSite: 'http://2019.ip138.com/ic.asp'

logging:
  level:
    com.example.servicehi.controller: debug
    com.example.servicehi.dao: debug
  config: classpath:loggback.xml