server:
  port: 8762

spring:
  application:
    name: service-hi
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://demo:3306/finalfantasyxiv?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: fell
    password: finalfantasyxiv
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
#    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#logging:
#  level: warn
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.servicehi.entity