server:
  port: 8762

spring:
  application:
    name: SERVICE-HI
  jackson:
    time-zone: GMT-8
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://demo:3306/finalfantasyxiv?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: fell
    password: finalfantasyxiv
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
  boot:
    admin:
      client:
        url: http://localhost:8791
  mail:
    host: smtp.qq.com
    username: 544107559@qq.com
    password: wbdagumkfakmbbjb
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.servicehi.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"

uploadImagePath:
  windows: 'D:/images'
  linux: '/root/uploadImage'

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.example.servicehi.dao : debug

delete_old_auth: true #删除旧权限